- title: "Plagiarism Allegations (2024)"
  year: 2024
  description: "In 2024, Kamala Harris was accused of plagiarism in several of her previous works. Passages from her 2009 book, 'Smart on Crime,' as well as her testimony before Congress in 2007, were allegedly copied without proper attribution."
  source: "https://nypost.com/2024/10/22/us-news/kamala-harris-accused-of-plagiarism-again-this-time-for-fabricating-a-sex-crime-and-cheating-off-a-former-ags-notes/"
  change_personal_context: false
  game_context: "Political scandal involving hush money during a presidential election."
  information_intensity: 5
- title: "Drug Case Management as District Attorney (2010)"
  year: 2010
  description: "In 2010, while serving as the San Francisco District Attorney, Harris's office was involved in a scandal related to a lab technician accused of stealing cocaine, leading to the dismissal of approximately 1,000 drug cases due to compromised evidence."
  source: "https://www.foxnews.com/politics/kamala-harris-failure-prosecutor-101-basics-led-hundreds-drug-convictions-being-tossed-out-expert"
  change_personal_context: false
  game_context: "Political scandal involving hush money during a presidential election."
  information_intensity: 5
- title: "Criticism of Human Trafficking Case Management (2012)"
  year: 2012
  description: "In 2012, as California Attorney General, Harris was criticized for using a fictional example of a human trafficking case, presented as real, in an official report."
  source: "https://nypost.com/2024/10/22/us-news/kamala-harris-accused-of-plagiarism-again-this-time-for-fabricating-a-sex-crime-and-cheating-off-a-former-ags-notes/"
  change_personal_context: false
  game_context: "Political scandal involving hush money during a presidential election."
  information_intensity: 5
- title: "Conflict of Interest Accusations with OneWest Bank (2013)"
  year: 2013
  description: "In 2013, Harris faced criticism for not prosecuting OneWest Bank, then led by Steven Mnuchin, for alleged violations of foreclosure laws, despite evidence of predatory practices."
  source: "https://en.wikipedia.org/wiki/Kamala_Harris_as_Attorney_General_of_California"
  change_personal_context: false
  game_context: "Political scandal involving hush money during a presidential election."
  information_intensity: 5
- title: "Controversy over Refusal to Defend Proposition 8 (2013)"
  year: 2013
  description: "In 2013, as California Attorney General, Harris refused to defend Proposition 8, a voter-approved ban on same-sex marriage, drawing criticism from some conservative groups."
  source: "https://en.wikipedia.org/wiki/Kamala_Harris_as_Attorney_General_of_California"
  change_personal_context: false
  game_context: "Political scandal involving hush money during a presidential election."
  information_intensity: 5
- title: "Criticism over Mismanagement of Wrongful Conviction Cases (2010)"
  year: 2010
  description: "Harris faced criticism for her handling of wrongful conviction cases, particularly that of Jamal Trulove, who was wrongfully convicted of murder during her tenure as San Francisco District Attorney."
  source: "https://www.the-sun.com/news/12218194/jamal-trulove-false-conviction-kamala-harris/"
  change_personal_context: false
  game_context: "Political scandal involving hush money during a presidential election."
  information_intensity: 5
- title: "Controversy over Denial of Medical Care to Transgender Inmates (2015)"
  year: 2015
  description: "In 2015, Harris was criticized for defending California's refusal to provide gender reassignment surgeries to transgender inmates, a position she later reversed."
  source: "https://www.washingtonblade.com/2015/05/05/harris-seeks-to-block-gender-reassignment-for-trans-inmate/"
  change_personal_context: false
  game_context: "Political scandal involving hush money during a presidential election."
  information_intensity: 5
- title: "Plagiarism Allegations in Official Reports (2012)"
  year: 2012
  description: "Allegations were made that Harris plagiarized sections of official reports as California Attorney General, using content from other prosecutors and judges without proper attribution."
  source: "https://nypost.com/2024/10/22/us-news/kamala-harris-accused-of-plagiarism-again-this-time-for-fabricating-a-sex-crime-and-cheating-off-a-former-ags-notes/"
  change_personal_context: false
  game_context: "Political scandal involving hush money during a presidential election."
  information_intensity: 5