- title: "Affaire Stormy Daniels"
  year: 2016
  description: "Michael Cohen, l'avocat de Donald Trump, a versé 130 000 $ à l'actrice pornographique Stormy Daniels pour acheter son silence concernant une liaison présumée en 2006. Trump a nié cette liaison, mais Cohen a admis que le paiement avait été effectué pour influencer l'élection présidentielle de 2016."
  source: "https://en.wikipedia.org/wiki/Stormy_Daniels–Donald_Trump_scandal"

- title: "Enregistrement Access Hollywood"
  year: 2005
  description: "Une vidéo de 2005 a refait surface en 2016, dans laquelle Donald Trump se vantait de comportements sexuels inappropriés envers les femmes, déclarant notamment : 'Quand vous êtes une star, elles vous laissent faire. Vous pouvez tout faire.' Ces commentaires ont été largement condamnés."
  source: "https://en.wikipedia.org/wiki/Donald_Trump_Access_Hollywood_tape"

- title: "Allégations d'inconduite sexuelle"
  description: "Plus de 25 femmes ont accusé Donald Trump de comportements sexuels inappropriés, y compris des attouchements non consensuels et des agressions sexuelles, remontant aux années 1970. Trump a nié toutes ces allégations, les qualifiant de fausses et politiquement motivées."
  source: "https://en.wikipedia.org/wiki/Donald_Trump_sexual_misconduct_allegations"

- title: "Ingérences russes dans l'élection de 2016"
  description: "L'enquête menée par le procureur spécial Robert Mueller a examiné les allégations de collusion entre la campagne de Trump et le gouvernement russe lors de l'élection présidentielle de 2016. Bien que le rapport Mueller n'ait pas conclu à une collusion criminelle, il n'a pas exonéré Trump d'obstruction à la justice."
  source: "https://apnews.com/article/trump-indictment-past-presidential-scandals-6fe9d423c42ea7fd945befcb4dd83704"

- title: "Première procédure de destitution"
  year: 2019
  description: "En 2019, Donald Trump a été mis en accusation par la Chambre des représentants pour abus de pouvoir et obstruction au Congrès, liés à ses demandes auprès de l'Ukraine pour enquêter sur Joe Biden et son fils. Il a été acquitté par le Sénat en 2020."
  source: "https://apnews.com/article/trump-indictment-past-presidential-scandals-6fe9d423c42ea7fd945befcb4dd83704"

- title: "Deuxième procédure de destitution"
  year: 2021
  description: "Après l'attaque du Capitole le 6 janvier 2021, Trump a été mis en accusation pour 'incitation à l'insurrection'. Il a de nouveau été acquitté par le Sénat, mais cette procédure a marqué la première fois dans l'histoire des États-Unis qu'un président était mis en accusation deux fois."
  source: "https://apnews.com/article/trump-indictment-past-presidential-scandals-6fe9d423c42ea7fd945befcb4dd83704"

- title: "Affaire E. Jean Carroll"
  year: 1996
  description: "En 2019, l'écrivaine E. Jean Carroll a accusé Donald Trump de l'avoir agressée sexuellement dans un grand magasin de New York dans les années 1990. Trump a nié les allégations, et Carroll a intenté une action en diffamation contre lui. En 2023, un jury a conclu que Trump était responsable d'abus sexuels et de diffamation, lui ordonnant de payer 5 millions de dollars en dommages et intérêts."
  source: "https://en.wikipedia.org/wiki/Donald_Trump_sexual_misconduct_allegations"

- title: "Affaire des documents classifiés"
  year: 2022
  description: "Après avoir quitté ses fonctions, il a été découvert que Donald Trump avait conservé des documents classifiés dans sa résidence de Mar-a-Lago, en Floride. Une enquête fédérale a été lancée pour déterminer s'il avait violé des lois sur la gestion des documents gouvernementaux."
  source: "https://apnews.com/article/trump-indictment-past-presidential-scandals-6fe9d423c42ea7fd945befcb4dd83704"

- title: "Fraude fiscale alléguée"
  year: 2023
  description: "En 2023, une enquête du procureur général de New York a conclu que la Trump Organization avait frauduleusement gonflé la valeur de ses actifs pour obtenir des prêts et des avantages fiscaux. Trump et ses enfants ont été poursuivis, et l'affaire est en cours."
