general_context:
  topic: "Political debate on national television"
  setting: "This debates takes place in a video game. Be funny, but avoid hateful speech"
  audience: "The speakers of the debate are trying to convince the audience to vote for them"
  requirements: 
    - "Response must be brief. Limit to less than 50 words."
  tone_guidelines: |
    Please craft a response following these guidelines:
    - **anger**: The closer the value is to 1, the more the response should be **rude**, **aggressive**, and **blunt**.
    - **anger**: The closer the value is to 0, the more the response should be **soft**, **gentle**, and **calm**. A lower anger value should reflect a peaceful, understanding tone.