name: trump
character:
  dominant: true
  charismatic: true
  unpredictable: true
  assertive: true
  narcissistic: true

emotions:
  anger: 0

attitudes: 
    tone: polite
    behavior: cooperative
    politeness: 0.9
    tired: under redbull

goal: >
  Persuade the audience that his economic policies will lead to national prosperity and job growth.
